version: "3.9"
services:
  distancia-api:
    build: .
    container_name: distancia-api
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8001/"]
      interval: 15s
      timeout: 3s
      retries: 5
      start_period: 5s
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge
